jobapp/urls.py
from django.urls import path
from .views import *
app_name = 'jobapp'

urlpatterns = [
    path('', JobSeekerHomeView.as_view(), name='jobseekerhome'),
    path('employer/', EmployerHomeView.as_view(), name='employerhome'),
    path('employer/profile/',EmployerProfileView.as_view(),name='employerprofile'),
    path('job-admin/', AdminHomeView.as_view(), name='adminhome'),
    path('jobseeker/registration/',
         JobSeekerRegistrationView.as_view(), name='jobseekerregister'),
    path('job/list/', JobListView.as_view(), name='joblist'),
    path('job/<int:pk>/detail/', JobDetailView.as_view(), name='jobdetail'),
    path('job/<int:pk>/apply/', JobSeekerJobApplyView.as_view(),
         name='jobseekerjobapply'),
    path('login/', LoginView.as_view(), name='login'),
    path('jobseeker/profile/', JobSeekerProfileView.as_view(),
         name='jobseekerprofile'),
    path('employer/registration', EmployerRegistrationView.as_view(),
         name='employerregistration'),
    path('employer/<int:pk>/detail/',EmployerDetailView.as_view(),name='employerdetail'),
    path('employer/job/<int:pk>/detail/',EmployerJobDetailView.as_view(),name='employerjobdetail'),
    path('employer/job/post/',EmployerJobCreateView.as_view(),name='employerjobcreate'),
    path('admin/profile/',AdminProfileView.as_view(),name='adminprofile'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('admin/employer/list/',AdminEmployerListView.as_view(),name='adminemployerlist'),
    path('admin/employer/<int:pk>/detail/',AdminEmployerDetailView.as_view(),name='adminemployerdetail'),
    path('admin/jobseeker/list/',AdminJobseekerListView.as_view(),name='adminjobseekerlist'),
    path('admin/jobseeker/<int:pk>/detail/',AdminJobSeekerDetailView.as_view(),name='adminjobseekerdetail'),
    path('admin/job/list/',AdminJobListView.as_view(),name='adminjoblist'),
    path('admin/job/<int:pk>/detail/',AdminJobDetailView.as_view(),name='adminjobdetail'),
    path('subscribe/',JobSeekerSubscribeView.as_view(),name='jobseekersubscribe'),
    path('subscriber/check/',SubscriberCheckView.as_view(),name='subscribercheck'),
    path('job-api/job/list/',ApiJobListView.as_view(),name='apijoblist'),
    path('job-api/job/<int:pk>/update/',ApiJobUpdateView.as_view(),name='apijobupdateview'),
]
    

jobproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jobapp.urls')),
    path('summernote/',include('django_summernote.urls')),
    path('django/rest',include('rest_framework.urls')),
]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/employertemplates/employerbase.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<title></title>
</head>
<body>
<a href="{% url 'jobapp:employerprofile' %}">Myprofile</a>
<a href="{% url 'jobapp:employerjobcreate' %}">EmployerJobCreate</a>

{% block content %}
{% endblock %}
</body>
</html>

templates/employertemplates/employerdetail.html
{% extends 'employertemplates/employerbase.html' %}
{% block content %}
<h1>employer detail</h1>
<h2>employername:{{employerdetail.name}}</h2>
<h3>employer website:{{employerdetail.website}}</h3>
<h3>employer mobile:{{employerdetail.mobile}}</h3>
{% endblock %}

templates/employertemplates/employerhome.html
{% extends 'employertemplates/employerbase.html' %}
{% block content %}
<h1>this is employer homepage</h1>
{% endblock %}

templates/employertemplates/employerjobcreate.html
{% extends 'employertemplates/employerbase.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}
<button>Submit</button>
</form>
{% endblock %}

templates/employertemplates/employerjobdetail.html
{% extends 'employertemplates/employerbase.html' %}
{% block content %}
<h1>employerjobdetail</h1>
<h3>jobtitle:{{jobobject.title}}</h3>
<h3>jobcreated:{{jobobject.created_at}}</h3>
<h4>jobcategory:{{jobobject.category}}</h4>
<h3>Job Application for this job</h3>
<table class='table'>
	<thead>
		<tr>
			<th>Sn</th>
			<th>applicant</th>
			<th>applied on</th>
			<th>downloadcv</th>
		<tr>
	</thead>

	<tbody>
		{% for application in jobobject.jobapplication_set.all %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td>{{application.jobseeker}}</td>
			<td>{{application.created_at}}</td>
			<td>
				<a href="{{application.jobseeker.cv.url}}" download>Download Cv</a>
				<a href="{{application.cover_letter.url}}" download>Download coverletter</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
	

</table>
{% endblock %}

templates/employertemplates/employerprofile.html
{% extends 'employertemplates/employerbase.html' %}
{% block content %}
<h1>my pro</h1>
<h1>{{employer.name}}</h1>
<h2>{{employer.email}}</h2>
<h3>{{employer.address}}</h3>
<h3>{{employer.mobile}}</h3>
<hr>
<h3>Job Posted by {{employer.compnay}}</h3>
<table class='table'>
	<thead>
		<tr>
			<th>Sn</th>
			<th>Job title</th>
			<th>Deadline</th>
			<th>Posted on</th>
		</tr>
		

	</thead>
	<tbody>
		{% for job in employer.job_set.all %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td><a href="{% url 'jobapp:employerjobdetail' job.id %}">{{job.title}}({{job.jobapplication_set.count}}application)</a></td>
			<td>{{job.deadline}}</td>
			<td>{{job.created_at}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock %}

templates/employertemplates/employerregistration.html
{% extends 'employertemplates/employerbase.html' %}
{% block content %}
<h1>EmployerRegistraion</h1>
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button>Submit</button>
	</form>
{% endblock %}