jobapp/urls.py
from django.urls import path
from .views import *
app_name = 'jobapp'

urlpatterns = [
    path('', JobSeekerHomeView.as_view(), name='jobseekerhome'),
    path('employer/', EmployerHomeView.as_view(), name='employerhome'),
    path('employer/profile/',EmployerProfileView.as_view(),name='employerprofile'),
    path('job-admin/', AdminHomeView.as_view(), name='adminhome'),
    path('jobseeker/registration/',
         JobSeekerRegistrationView.as_view(), name='jobseekerregister'),
    path('job/list/', JobListView.as_view(), name='joblist'),
    path('job/<int:pk>/detail/', JobDetailView.as_view(), name='jobdetail'),
    path('job/<int:pk>/apply/', JobSeekerJobApplyView.as_view(),
         name='jobseekerjobapply'),
    path('login/', LoginView.as_view(), name='login'),
    path('jobseeker/profile/', JobSeekerProfileView.as_view(),
         name='jobseekerprofile'),
    path('employer/registration', EmployerRegistrationView.as_view(),
         name='employerregistration'),
    path('employer/<int:pk>/detail/',EmployerDetailView.as_view(),name='employerdetail'),
    path('employer/job/<int:pk>/detail/',EmployerJobDetailView.as_view(),name='employerjobdetail'),
    path('employer/job/post/',EmployerJobCreateView.as_view(),name='employerjobcreate'),
    path('admin/profile/',AdminProfileView.as_view(),name='adminprofile'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('admin/employer/list/',AdminEmployerListView.as_view(),name='adminemployerlist'),
    path('admin/employer/<int:pk>/detail/',AdminEmployerDetailView.as_view(),name='adminemployerdetail'),
    path('admin/jobseeker/list/',AdminJobseekerListView.as_view(),name='adminjobseekerlist'),
    path('admin/jobseeker/<int:pk>/detail/',AdminJobSeekerDetailView.as_view(),name='adminjobseekerdetail'),
    path('admin/job/list/',AdminJobListView.as_view(),name='adminjoblist'),
    path('admin/job/<int:pk>/detail/',AdminJobDetailView.as_view(),name='adminjobdetail'),
    path('subscribe/',JobSeekerSubscribeView.as_view(),name='jobseekersubscribe'),
    path('subscriber/check/',SubscriberCheckView.as_view(),name='subscribercheck'),
    path('job-api/job/list/',ApiJobListView.as_view(),name='apijoblist'),
    path('job-api/job/<int:pk>/update/',ApiJobUpdateView.as_view(),name='apijobupdateview'),
]
    

jobproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jobapp.urls')),
    path('summernote/',include('django_summernote.urls')),
    path('django/rest',include('rest_framework.urls')),
]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/admintemplates/adminbase.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'jobseekerstatic/css/bootstrap.min.css' %}">
	{% block css %}
	{% endblock %}
</head>
<body class="container">
	<nav class="nav">

	<ul>
		<li>
			<a href="{% url 'jobapp:adminhome' %}">Home</a>
			<a href="">About</a>
			<li>logged in as :{{request.user}}</li>
			<a href="{% url 'jobapp:adminprofile' %}">AdminProfile</a>
			<a href="{% url 'jobapp:logout' %}">Logout</a>
		</li>
		
	</ul>
</nav>

{% block content %}
{% endblock %}
<script
  src="https://code.jquery.com/jquery-3.4.0.min.js"
  integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg="
  crossorigin="anonymous"></script>
{% block js %}
{% endblock  %}
</body>
</html>

templates/admintemplates/adminemployerdetail.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<h1>AdminEmployerDetail</h1>
<table class="table">
	<thead>
		<tr>
			<th>EmployerName</th>
			<th>EmployerAddress</th>
			<th>Employer mobile</th>
		</tr>

	</thead>
	<tbody>
		<tr>
			<td>{{adminemployerobject.name}}</td>
			<td>{{adminemployerobject.address}}</td>
			<td>{{adminemployerobject.mobile}}</td>
		</tr>
	</tbody>
	

</table>
{% endblock %}

templates/admintemplates/adminemployerlist.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<h1>Employer Detail</h1>
<table class="table">
	<thead>
		<tr>
			<th>Sn</th>
			<th>Employer Name:</th>
			<th>Employer mobile:</th>
		</tr>
	</thead>
	<tbody>
		{% for employer in adminemployer %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td><a href="{% url 'jobapp:adminemployerdetail' employer.id %}">{{employer.name}}</td>
				<td>{{employer.mobile}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock %}

templates/admintemplates/adminhome.html
{% extends 'admintemplates/adminbase.html' %}
{% block css %}
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css">
{% endblock %}
{% block content %}
<h1>this is Admin HomePage</h1>
<div class="row">
	<div class="col-md-3 bg-success p-3">
		<h3 class="text-center text-white">{{allemployers.count}}</h3>
		<h4 class="text-center">Employers</h4>
	</div>
	<div class="col-md-3 bg-warning p-3">
		<h3 class="text-center text-white">{{alljobs.count}}</h3>
		<h4 class="text-center">Jobs</h4>

	</div>
	<div class="col-md-3 bg-info p-3">
		<h3 class="text-center text-white">{{alljobseekers.count}}</h3>
		<h4 class="text-center">Jobseeker</h4>

	</div>
	<div class="col-md-3 bg-danger p-3">
		<h3 class="text-center text-white">{{allapplications.count}}</h3>
		<h4 class="text-center">JobApplication</h4>
	</div>
	</div>
	<div class="row">
		<div class="col-md-6">
            <h3>Employers Statistics</h3></hr>
			<canvas id="myChart" width="400" height="400"></canvas>
		</div>
        <div class="col-md-6">
            <h3>Job Statistics</h3></hr>
            <canvas id="jobChart" width="400" height="400"></canvas>
        </div>
	</div>

{% endblock %}
{% block js %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
<script>
var ctx = document.getElementById('myChart');
var myChart = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: [{% for employer in allemployers %}"{{employer.compnay}}",{% endfor %}],
        datasets: [{
            label: '# Job Statistic',
            data: [{% for employer in allemployers %}"{{employer.job_set.all.count}}",{% endfor %}],
            backgroundColor: [
            '#799746',
                // 'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
               
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
var job = document.getElementById('jobChart');
var jobChart = new Chart(job, {
    type: 'bar',
    data: {
        labels: [{% for job in alljobs %}"{{job.title}}",{% endfor %}],
        datasets: [{
            label: '# Job Statistic',
            data: [{% for job in alljobs %}"{{job.jobapplication_set.all.count}}",{% endfor %}],
            backgroundColor: [
            '#799746',
                // 'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
               
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>
{% endblock %}

templates/admintemplates/adminjobdetail.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<h1>JobDetail</h1>
<table class="table">
	<thead>
		<tr>
			<th>Title</th>
			<th>Image</th>
			<th>Type</th>
			<th>Level</th>
		</tr>

	</thead>
	<tbody>
	<td>{{jobdetailobject.title}}</td>
	<td><img src="{{jobdetailobject.image.url}}" width="200"></td>
	<td>{{jobdetailobject.job_type}}</td>
	<td>{{jobdetailobject.level}}</td>

	</tbody>
	
</table>
{% endblock %}

templates/admintemplates/adminjoblist.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<h1>JobList</h1>
<table class="table">
	<thead>
		<tr>
			<th>Sn</th>
			<th>JobTitle</th>
			<th>Image</th>
		
		</tr>

		

	</thead>
	<tbody>
		{% for job in jobobject %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td><a href="{% url 'jobapp:adminjobdetail' job.id %}">{{job.title}}</td>
			<td><img src="{{job.image.url}}" width="200"></td>
			
		</tr>
		{% endfor %}
	</tbody>
	

</table>

{% endblock %}

templates/admintemplates/adminjobseekerdetail.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<h1>JobSeekeerDetailView</h1>
<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Address</th>
			<th>Mobile</th>
			<th>Skills</th>
		</tr>
	</thead>
	<tbody>
		<td>{{jobseekerdetailobject.name}}</td>
		<td>{{jobseekerdetailobject.address}}</td>
		<td>{{jobseekerdetailobject.mobile}}</td>
		<td>{{jobseekerdetailobject.skills}}</td>

	</tbody>
	
</table>
{% endblock %}

templates/admintemplates/adminjobseekerlist.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<h1>JobSeekerList</h1>
<table class="table">
	<thead>
		<tr>
			<th>Sn</th>
			<th>name</th>
			<th>address</th>
		</tr>
	</thead>
	<tbody>
		{% for jobseeker in jobseekerobject %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td><a href="{% url 'jobapp:adminjobseekerdetail' jobseeker.id %}">{{jobseeker.name}}</td>
			<td>{{jobseeker.address}}</td>

		</tr>
		{% endfor %}
	</tbody>

	

</table>

{% endblock %}

templates/admintemplates/adminprofile.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<h1 id="myh1">Admin Profile</h1>
<hr>
<input type='text' value='' id ="myinput" >
<h2>{{admin.name}}</h2>
<h3>{{admin.address}}</h3>
<h4>{{admin.mobile}}</h4>
<hr>
<h1>Employer Information</h1>
<table class="table">
	<thead>
		<tr>
			<th>Sn</th>
			<th>Employer Name</th>
			<th>Mobile</th>
		</tr>
	</thead>
		<tbody>
			{% for employer in allemployers %}
			<tr>
				<td>{{forloop.counter}}</td>
				<td>{{employer.name}}</td>
				<td>{{employer.mobile}}</td>
			</tr>
		
			{% endfor %}
			

		</tbody>


	

</table>
<hr>
<h1>JobseekerInformation</h1>
<table class="table">
	<thead>
		<tr>
			<th>Sn</th>
			<th>joseeker name</th>
			<th>address</th>
			<th>mobile</th>
		</tr>

	</thead>
	<tbody>
		{% for jobseeker in alljobseekers %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td>{{jobseeker.name}}</td>
			<td>{{jobseeker.address}}</td>
			<td>{{jobseeker.mobile}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock %}
{% block js %}
<script >
	// alert("hello wolrd");
	// document.getElementById('myh1').style.color='red';
	// document.getElementById('myinput').value="my";
	// var el=document.getElementById("myinput")
	// el.type='hidden'
	$('#myh1')
	$('#myinput').on('change',function(){
		var value = $(this).val();
		alert(value);
	})
	
</script>
{% endblock %}