jobapp/urls.py
from django.urls import path
from .views import *
app_name = 'jobapp'

urlpatterns = [
    path('', JobSeekerHomeView.as_view(), name='jobseekerhome'),
    path('employer/', EmployerHomeView.as_view(), name='employerhome'),
    path('employer/profile/',EmployerProfileView.as_view(),name='employerprofile'),
    path('job-admin/', AdminHomeView.as_view(), name='adminhome'),
    path('jobseeker/registration/',
         JobSeekerRegistrationView.as_view(), name='jobseekerregister'),
    path('job/list/', JobListView.as_view(), name='joblist'),
    path('job/<int:pk>/detail/', JobDetailView.as_view(), name='jobdetail'),
    path('job/<int:pk>/apply/', JobSeekerJobApplyView.as_view(),
         name='jobseekerjobapply'),
    path('login/', LoginView.as_view(), name='login'),
    path('jobseeker/profile/', JobSeekerProfileView.as_view(),
         name='jobseekerprofile'),
    path('employer/registration', EmployerRegistrationView.as_view(),
         name='employerregistration'),
    path('employer/<int:pk>/detail/',EmployerDetailView.as_view(),name='employerdetail'),
    path('employer/job/<int:pk>/detail/',EmployerJobDetailView.as_view(),name='employerjobdetail'),
    path('employer/job/post/',EmployerJobCreateView.as_view(),name='employerjobcreate'),
    path('admin/profile/',AdminProfileView.as_view(),name='adminprofile'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('admin/employer/list/',AdminEmployerListView.as_view(),name='adminemployerlist'),
    path('admin/employer/<int:pk>/detail/',AdminEmployerDetailView.as_view(),name='adminemployerdetail'),
    path('admin/jobseeker/list/',AdminJobseekerListView.as_view(),name='adminjobseekerlist'),
    path('admin/jobseeker/<int:pk>/detail/',AdminJobSeekerDetailView.as_view(),name='adminjobseekerdetail'),
    path('admin/job/list/',AdminJobListView.as_view(),name='adminjoblist'),
    path('admin/job/<int:pk>/detail/',AdminJobDetailView.as_view(),name='adminjobdetail'),
    path('subscribe/',JobSeekerSubscribeView.as_view(),name='jobseekersubscribe'),
    path('subscriber/check/',SubscriberCheckView.as_view(),name='subscribercheck'),
    path('job-api/job/list/',ApiJobListView.as_view(),name='apijoblist'),
    path('job-api/job/<int:pk>/update/',ApiJobUpdateView.as_view(),name='apijobupdateview'),
]
    

jobproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jobapp.urls')),
    path('summernote/',include('django_summernote.urls')),
    path('django/rest',include('rest_framework.urls')),
]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

jobapp/models.py
from django.db import models
from django.contrib.auth.models import User,Group

# Create your models here.


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Admin(TimeStamp):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=100)
    email = models.EmailField()
    address = models.CharField(max_length=100)
    image = models.ImageField(upload_to='admin')
    name = models.CharField(max_length=100)
    def save(self,*args,**kwargs):
        group,created=Group.objects.get_or_create(name='admin')
        self.user.groups.add(group)
        super().save(*args,**kwargs)

    def __str__(self):
        return self.name


class Employer(TimeStamp):
    user = models.OneToOneField(User, on_delete=models.CharField)
    name = models.CharField(max_length=100)
    mobile = models.CharField(max_length=100)
    email = models.EmailField()
    address = models.CharField(max_length=100)
    image = models.ImageField(upload_to='employer')
    website = models.CharField(max_length=100)
    compnay = models.CharField(max_length=100)
    company_image = models.ImageField(upload_to='employer')
    
    def save(self,*args,**kwargs):
        group,created=Group.objects.get_or_create(name='employer')
        self.user.groups.add(group)
        super().save(*args,**kwargs)

    def __str__(self):
        return self.name




class JobSeeker(TimeStamp):
    user = models.OneToOneField(User, on_delete=models.CharField)
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    mobile = models.CharField(max_length=100)
    image = models.ImageField(upload_to='jobseeker')
    qualification = models.CharField(max_length=100)
    skills = models.CharField(max_length=100)
    about = models.CharField(max_length=100)
    cv = models.FileField(upload_to='jobseeker')
    views_count = models.PositiveIntegerField(default=0)

    def save(self,*args,**kwargs):
        group,created=Group.objects.get_or_create(name='jobseeker')
        self.user.groups.add(group)
        super().save(*args,**kwargs)

    def __str__(self):
        return self.name


class JobCategory(TimeStamp):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='jobcategory')

    def __str__(self):
        return self.title


JOB_TYPE = (('full_time', 'Full Time'), ('part_time', 'Part Time'),
            ('contact', 'Contact'), ('internship', 'Internship'),)
LEVEL = (('junior', 'Junior'), ('mid', 'Mid'), ('seneior', 'Seneior'),)


class Job(TimeStamp):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='job')
    category = models.ForeignKey(JobCategory, on_delete=models.CASCADE)
    job_type = models.CharField(max_length=100, choices=JOB_TYPE)
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE)
    level = models.CharField(max_length=50, choices=LEVEL)
    deadline = models.DateTimeField()
    vaccncy_number = models.PositiveIntegerField()
    education = models.CharField(max_length=100)
    skills = models.CharField(max_length=100)
    details = models.TextField()
    views_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class JobApplication(TimeStamp):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    jobseeker = models.ForeignKey(JobSeeker, on_delete=models.CASCADE)
    cover_letter = models.FileField(upload_to='jobapplication')

    def __str__(self):
        return self.jobseeker.name
class Subscriber(TimeStamp):
    email=models.EmailField()

    def __str__(self):
        return self.email

templates/jobseekertemplates/error.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% block content %}
<li>{{error}}</li>
{% endblock %}

templates/jobseekertemplates/jobdetail.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% block content %}
<!-- <h1>(views :{{jobseekerdetail.views_count}})
<h1>this is the detail view</h1>
<h1>{{jobseekerdetail.name}}</h1>
<p>{{jobseekerdetail.about}}</p>
<img src="{{jobseekerdetail.image.url}}" width="200"> -->
<h1>Job Detail</h1>
<a href="{% url 'jobapp:jobseekerjobapply' jobdetail.id %}">ApplyNow</a>
<h1>{{jobdetail.title}}</h1>
<h2>{{jobdetail.skills}}</h2>
<img src="{{jobdetail.image.url}}" width="200">
<h3>{{jobdetail.details|safe}}</h3>
<div class="fb-like" data-href="{{request.build_absolute_uri}}" data-width="" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
<div class="fb-comments" data-href="{{request.build_absolute_uri }}" data-width="" data-numposts="5"></div>
{% endblock %}

templates/jobseekertemplates/joblist.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% load static %}
{% block content %}
<h1>this is the Job List view</h1>
<div class="row">
	<div class="col-md-9">
		<div class="row">
			{% for job in joblist %}
			<div class="col-md-4">
					
				<a href="{% url 'jobapp:jobdetail' job.id %}">{{job.title}}</a><br>
				<img src="{{job.image.url}}" width="200" class="img-fluid">
				<h1>{{job.skills}}</h1>
				<h2>{{job.educations}}</h2>
			</div>
			{% endfor %}
		</div>
		
	</div>
	<div class="col-md-3">
		<h3>LatestJobs</h3>
		{% for job in joblist %}
		<div class="col-md-12">
			<li><a href="{% url 'jobapp:jobdetail' job.id %}">{{job.title}}
			</a></li>
			<h1>{{job.skills}}</h1>
			<h2>{{job.educations}}</h2>
		</div>
	{% endfor %}
	</div>

</div>



{% endblock %}

templates/jobseekertemplates/jobseekerbase.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'jobseekerstatic/css/bootstrap.min.css' %}">
</head>
<body>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.3"></script>
	<h1>email is send</h1>
		{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
	{% if request.user.is_authenticated and request.user.groups.first.name == 'jobseeker' %}																			
	<h5>logged in as:{{request.user}}</h5>
	<a href="{% url 'jobapp:jobseekerprofile' %}">MyProfile</a>
	{% else %}
	<a href="">login</a>
	<a href="{% url 'jobapp:jobseekerregister' %}">Register</a>
	{% endif %}
	<a href="{% url 'jobapp:jobseekerhome' %}">Home</a>


	{% block content %}
	{% endblock %}

	<div class="row">
		<div class="col-md-12">
			<form method="post" action="{% url 'jobapp:jobseekersubscribe' %}">
				<p id ='errorp'></p>
				{% csrf_token %}
				{{subform.as_p}}
				
				<button id="mybutton">Subscribe</button>
			</form>
		</div>
	</div>
	<script
  src="https://code.jquery.com/jquery-3.4.0.min.js"
  integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg="
  crossorigin="anonymous"></script>


<script>
	$('#id_email').on('keyup',function(){
		var email = $(this).val();
		$.ajax({
			url:"{% url 'jobapp:subscribercheck' %}",
			data:{'email':email},
		success:function(data){
			if(data.error=='error')
			{$('#errorp').text('subscriber already exists');
		     $('#mybutton').attr('disabled',true);


			}
			else
			{
				$('#errorp').text('you can subscribe this email');
		     $('#mybutton').removeAttr('disabled');

			}
		}

	})
	})
</script>




    <script type="text/javascript" src="{% static 'jobseekerstatic/js/jquery-3.4.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'jobseekerstatic/js/bootstrap.bundle.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'jobseekerstatic/js/bootstrap.min.js' %}"></script>
	<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5cc94a292846b90c57ac4f71/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->
</body>
</html>

templates/jobseekertemplates/jobseekerhome.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% block content  %}
{% load static %}
<h1>this is JOB  Home page</h1>
<h2>JobList</h2>
{% for job in jobs %}
<img src="{{job.image.url}}" width="200">
<h2>{{job.level}}</h2>
{% endfor %}
<div class="fb-page" data-href="https://www.facebook.com/SarobarTechnology/" data-tabs="timeline" data-width="" data-height="" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/SarobarTechnology/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/SarobarTechnology/">Sarobar Technology Pvt. Ltd</a></blockquote></div>
{% endblock %}

templates/jobseekertemplates/jobseekerjobapply.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% load static %}
{% block content %}
<h1>Job Application Form</h1>
<form method='post' enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p }}
	<button>Apply</button>

	</form>
{% endblock %}

templates/jobseekertemplates/jobseekerprofile.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% block content %}
<h3>My Profile</h3>
<hr>
<h4>Name:{{jobseeker.name}}</h4>
<h3>Job I have Applied</h3>
</hr>
<table class='table'>
	<thead>
		<tr>
		<th>SN</th>
		<th>JobTitle</th>
		<th>Company</th>
		<th>Date</th>
		</tr>
	</thead>
	<tbody>
		{% for jobapplication in jobseeker.jobapplication_set.all %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td>{{jobapplication.job.title}}</td>
			<td>{{jobapplication.job.employer.compnay}}</td>
			<td>{{jobapplication.created_at}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

templates/jobseekertemplates/jobseekerregisteration.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button>Register</button>


	</form>

{% endblock %}

templates/jobseekertemplates/login.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% block content %}
{% if error %}
<li>{{error}}</li>
{% endif %}
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button>LOGIN</button>
</form>
<h4>Don't have account ?</h4>
<a href="{% url 'jobapp:jobseekerregister' %}">Register as Jobseeker</a>
or
<a href="{% url 'jobapp:employerregistration' %}">Register as Employer</a>
{% endblock %}